FROM oven/bun:1.3.11-alpine

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY src ./src
COPY drizzle.config.ts ./
COPY tsconfig.json ./

RUN chown -R appuser:appgroup /app
USER appuser

CMD ["bun", "run", "--bun", "drizzle-kit", "migrate"]
